[package]
name = "nullnet-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
nullnet-core.workspace = true
bevy = { version = "0.19.1", default-features = false, features = ["2d", "ui"] }
ehttp = { version = "0.7.1", features = ["json"] }
nullnet-api.workspace = true
serde = { workspace = true, features = ["derive"] }

[target.wasm32-unknown-unknown.dependencies]
web-sys = { version = "0.3.106", features = ["Window", "Location"] }
